name: Merge Script

on:
  schedule:
    - cron: '0 4 * * *'  # 每天北京时间12点执行
  workflow_dispatch:  # 触发手动事件

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        run: python meta_merge.py 

      - name: Run shadowrocket merge script
        run: python merge.py  

      - name: Check for changes
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit Changes
        run: |
          git config core.ignorecase false
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        if: steps.git-check.outputs.modified == 'true'
